project:
  type: website
  output-dir: docs

website:
  title: "harishnkr"
  site-url: "https://www.harishnkr.in"
  description: "K. Harishankar's site"
  navbar:
    left:
      - href: bookmarks.qmd
        text: Bookmarks
      - href: posts.qmd
    right:
      - icon: rss
        href: posts.xml
      - icon: github
        href: https://www.github.com/harishnkr

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

resources:
  - CNAME

