project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: harishnkr
      - href: bookmarks.qmd
        text: Bookmarks
      - href: posts.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

resources:
  - CNAME

